import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='homePage'>
        <div>
          <h1>Singleplayer</h1>
          <div className='gameModes'>
          <Link className='modes' href="/gamemodes/quotes">
            Quotes
          </Link>
          <Link className='modes' href="/gamemodes/random">
            Random words
          </Link>
          <Link className='modes' href="/gamemodes/timed">
            Timed run
          </Link>
          <Link className='modes' href="/gamemodes/custom">
            Custom
          </Link>
          </div>
        </div>
        <div><h1>Multiplayer</h1></div>
        </div>
      </main>
    </>
  )
}
